[package]
name = "chess"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = { version = "0.28.1", default-features = false, features = ["event-stream"]}

[profile.release]
opt-level = 3
debug = false
rpath = false
debug-assertions = false
codegen-units = 1
lto = true
